### PR TITLE
atc.captainwebservices.com/postID + Some other stuff

### PR DESCRIPTION
**Pull request by haylinmoore**
It sets it up so posts are now atc.captainwebservices.com/postID which is better for SEO support. Redirect index.php to / and change links from index.php to /
Also will turn url into a link

### CODE REVIEW

**Comment by haylinmoore** [comment]
*Gets email saying it was merged.* *Fist bumps air and saying YEAH*

**Comment by lholliger** [comment]
errr some stuff broke

**Comment by haylinmoore** [comment]
.htaccess? was that sent to your server?

**Comment by lholliger** [comment]
i restarted apache2 and i did a git pull

**Comment by haylinmoore** [comment]
Hmmmm

**Comment by haylinmoore** [comment]
https://stackoverflow.com/questions/12202387/htaccess-not-working-apache

**Comment by haylinmoore** [comment]
here follow these

**Comment by lholliger** [comment]
can i just throw .htaccess in the 000-default.conf file vhost and hope for the best?

**Comment by haylinmoore** [comment]
I guess. I use nginx so I was just running a Mamp apache server.

**Comment by lholliger** [comment]
lets check now

**Comment by haylinmoore** [comment]
just add AllowOverride All to the vhosts

**Comment by lholliger** [comment]
theres like 15 of them

**Comment by lholliger** [comment]
i put it in and it does the same thing: take you to a page that is the ID

**Comment by haylinmoore** [comment]
run
sudo a2enmod rewrite
then 
add

<Directory "/var/www/loction">
  AllowOverride All
</Directory>

**Comment by haylinmoore** [comment]
it should and the ID page should show the post

**Comment by lholliger** [comment]
i did it. it must be something wrong with the pull

**Comment by haylinmoore** [comment]
IT WORKS!

**Comment by haylinmoore** [comment]
https://atc.captainwebservices.com/592857a85b5cb

**Comment by lholliger** [comment]
YEEEESSSSS

**Comment by lholliger** [comment]
should we do something like post/id so it looks a little better?

**Comment by haylinmoore** [comment]
Ok if you can get it to work then yeah

**Comment by lholliger** [comment]
cool, but so far it works great, thx

**Pull request merged**
